import React from 'react';
// import components 
import Todo from './Todo';
/* This component returns a mapped todo list that 
 * contains every todo item generated by user input. 
 * filteredTodos is used to properly display the state of each item 
 * whenever user toggles the select button.
 */
const TodoList = ({ filteredTodos, setTodos, todos }) => {
    return(
        <div className="todo-container">
            <ul className="todo-list">
                { // map out every todo items, hence displays all todos
                 filteredTodos.map(todo => (
                    <Todo 
                        setTodos={setTodos} 
                        todos={todos}
                        key={todo.id} // add a key to each todo item
                        todo={todo}
                        text={todo.text}
                    />
                ))
                }
            </ul>
        </div>
    );
};

export default TodoList;